Car Accident dataset Preview

In [1]:
import pandas as pd

url = "https://media.githubusercontent.com/media/KhalPrawira/Big-Data_Assignment/refs/heads/main/Dataset/Road%20Accident%20Data.csv"
df = pd.read_csv(url)

display(df.head())

,Accident_Index,Accident Date,Day_of_Week,Junction_Control,Junction_Detail,Accident_Severity,Latitude,Light_Conditions,Local_Authority_(District),Carriageway_Hazards,...,Number_of_Casualties,Number_of_Vehicles,Police_Force,Road_Surface_Conditions,Road_Type,Speed_limit,Time,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200901BS70001,1/1/2021,Thursday,Give way or uncontrolled,T or staggered junction,Serious,51.512273,Daylight,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Dry,One way street,30,15:11,Urban,Fine no high winds,Car
1,200901BS70002,1/5/2021,Monday,Give way or uncontrolled,Crossroads,Serious,51.514399,Daylight,Kensington and Chelsea,NaN,...,11,2,Metropolitan Police,Wet or damp,Single carriageway,30,10:59,Urban,Fine no high winds,Taxi/Private hire car
2,200901BS70003,1/4/2021,Sunday,Give way or uncontrolled,T or staggered junction,Slight,51.486668,Daylight,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Dry,Single carriageway,30,14:19,Urban,Fine no high winds,Taxi/Private hire car
3,200901BS70004,1/5/2021,Monday,Auto traffic signal,T or staggered junction,Serious,51.507804,Daylight,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Frost or ice,Single carriageway,30,8:10,Urban,Other,Motorcycle over 500cc
4,200901BS70005,1/6/2021,Tuesday,Auto traffic signal,Crossroads,Serious,51.482076,Darkness - lights lit,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Dry,Single carriageway,30,17:25,Urban,Fine no high winds,Car

In [2]:
df['Local_Authority_(District)_cleaned'] = df['Local_Authority_(District)'].astype(str).str.replace(' and ', ' ', regex=False).str.strip()

district_percentages = df['Local_Authority_(District)_cleaned'].value_counts(normalize=True) * 100

display(district_percentages)

Local_Authority_(District)_cleaned
Birmingham            2.001799
Leeds                 1.344274
Manchester            1.016972
Bradford              0.976060
Westminster           0.912742
                        ...
Clackmannanshire      0.008118
Alnwick               0.006494
South Shropshire      0.005845
Teesdale              0.004871
Berwick-upon-Tweed    0.004221
Name: proportion, Length: 422, dtype: float64

In [3]:
district_counts = df['Local_Authority_(District)'].value_counts()
display(district_counts)

Local_Authority_(District)
Birmingham            6165
Leeds                 4140
Manchester            3132
Bradford              3006
Westminster           2811
                      ...
Clackmannanshire        25
Alnwick                 20
South Shropshire        18
Teesdale                15
Berwick-upon-Tweed      13
Name: count, Length: 422, dtype: int64

In [5]:
district_counts.to_excel('district_counts.xlsx', sheet_name='District Counts')

print("Data 'district_counts' telah berhasil diekspor ke 'district_counts.xlsx'")

Data 'district_counts' telah berhasil diekspor ke 'district_counts.xlsx'

In [ ]:
num_unique_districts = df['Local_Authority_(District)'].nunique()
print(f"Jumlah tipe (nilai unik) dalam kolom Local_Authority_(District): {num_unique_districts}")

Jumlah tipe (nilai unik) dalam kolom Local_Authority_(District): 422