<a href="https://colab.research.google.com/github/KhalPrawira/Big-Data_Assignment/blob/main/Code/Analisis_Data_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Proyek Analisis Data: Global Air Quality Polution

A. Pertanyaan terkait informasi Negara Indonesia


1. Ada berapa kota di negara Indonesia dan apa saja kota-kota yang terdapat di dalam dataset?
2. Berapa nilai AQI Value untuk setiap kota di Indonesia yang terdata?
3. Berapa nilai rata-rata AQI Value untuk setiap kota di Indonesia tersebut?
4. Bagaimana urutan Kota-kota tersebut dari rata-rata AQI Value terendah hingga tertinggi untuk menemukan 3 teratas?
5. Dari kota-kota dengan udara terbersih di Indonesia, apakah ada yang memiliki komponen polusi (misalnya PM2.5) dengan kategori di atas 'Baik' (Good)

In [22]:
import pandas as pd

df = pd.read_csv('https://media.githubusercontent.com/media/KhalPrawira/Big-Data_Assignment/refs/heads/main/Dataset/global%20air%20pollution%20dataset.csv')
display(df.head())

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good

1. ada berapa kota di negara Indonesia dan apa saja kota-kota yang terdapat di dalam dataset?

In [23]:
num_indonesia_cities = len(indonesia_cities)

display(f"Total kota di negara Indonesia: {num_indonesia_cities}")

'Total kota di negara Indonesia: 379'

In [24]:
indonesia_cities_df = df[df['Country'] == 'Indonesia']

indonesia_cities = indonesia_cities_df['City'].unique()

display("Kota di Indonesia:")
display(indonesia_cities)

'Kota di Indonesia:'

array(['Pontianak', 'Tidore', 'Sungaipenuh', 'Tarogong', 'Binjai',
       'Pamekasan', 'Prabumulih', 'Pringsewu', 'Lubuk Pakam', 'Mojoagung',
       'Lamongan', 'Karang Tengah', 'Kembaran', 'Malang', 'Kutoarjo',
       'Mataram', 'Mertoyudan', 'Driyorejo', 'Ngaglik', 'Purwakarta',
       'Palembang', 'Pameungpeuk', 'Leuwiliang', 'Sidareja', 'Wlingi',
       'Mlonggo', 'Ngoro', 'Ciampea', 'Balaipungut', 'Bandung',
       'Boyolali', 'Brebes', 'Sabang', 'Sumber', 'Waingapu', 'Balung',
       'Wanaraja', 'Sukaraja', 'Prigen', 'Sibolga', 'Sumbawa',
       'Klangenan', 'Kebonarum', 'Kebumen', 'Sidoarjo', 'Kaliwungu',
       'Genteng', 'Gatak', 'Cileungsi', 'Ciranjang', 'Banjarmasin',
       'Pacet', 'Wonosobo', 'Weleri', 'Martapura', 'Surabaya',
       'Bojonegoro', 'Bone', 'Gresik', 'Sijunjung', 'Sleman', 'Talang',
       'Lebaksiu', 'Manado', 'Salatiga', 'Sepatan', 'Pamulang', 'Pandaan',
       'Parung', 'Banjar', 'Bogor', 'Muntilan', 'Ciparay', 'Tegal',
       'Tuban', 'Gebog', 'Pamanukan', 'Merauke', 'Karanganom', 'Bekasi',
       'Ciledug', 'Ubud', 'Sunggal', 'Praya', 'Curug', 'Pandegelang',
       'Peterongan', 'Bangkalan', 'Kudus', 'Majalengka', 'Diwek',
       'Dukuhturi', 'Gedangan', 'Mlati', 'Sindang', 'Simpang',
       'Tulungagung', 'Seyegan', 'Mranggen', 'Wonosari', 'Atambua',
       'Cirebon', 'Deli Tua', 'Jombang', 'Tebingtinggi', 'Wedi', 'Majene',
       'Kebomas', 'Medan', 'Belawan', 'Singojuruh', 'Purworejo',
       'Bumiayu', 'Banyumas', 'Baturaden', 'Karangsembung', 'Gombong',
       'Singosari', 'Mojosari', 'Jaten', 'Kendari', 'Polewali', 'Padang',
       'Citeureup', 'Trenggalek', 'Pangkalanbuun', 'Banjaran', 'Ciamis',
       'Ciawi', 'Cilegon', 'Godean', 'Jepara', 'Kadungora',
       'Ketanggungan', 'Yogyakarta', 'Sampit', 'Sragen', 'Pare',
       'Pemalang', 'Taman', 'Ende', 'Banda Aceh', 'Plumbon', 'Gambiran',
       'Gampengrejo', 'Gempol', 'Loa Janan', 'Manokwari', 'Paseh',
       'Singkang', 'Singkawang', 'Negara', 'Panarukan', 'Babakan',
       'Cileunyi', 'Tomohon', 'Bengkalis', 'Cidahu', 'Delanggu', 'Srono',
       'Kepanjen', 'Kawalu', 'Tangerang', 'Bae', 'Cisarua', 'Wonogiri',
       'Gorontalo', 'Purbalingga', 'Ceper', 'Maumere', 'Dampit', 'Bitung',
       'Pekalongan', 'Pemangkat', 'Babat', 'Kresek', 'Sewon', 'Semarang',
       'Rangkasbitung', 'Rantauprapat', 'Buaran', 'Soreang', 'Grogol',
       'Pecangakan', 'Dumai', 'Lahat', 'Lhokseumawe', 'Samarinda',
       'Sampang', 'Cikeruh', 'Cimahi', 'Sigli', 'Situbondo', 'Lawang',
       'Magelang', 'Nabire', 'Pedan', 'Waru', 'Kanigoro', 'Kedungwuni',
       'Comal', 'Gondanglegi', 'Garut', 'Karangasem', 'Karawang',
       'Serang', 'Perbaungan', 'Jogonalan', 'Klaten', 'Tondano',
       'Bambanglipuro', 'Singaraja', 'Bulakamba', 'Cisaat', 'Cianjur',
       'Cibinong', 'Besuki', 'Rengasdengklok', 'Ruteng', 'Sukabumi',
       'Balapulang', 'Jember', 'Tambun', 'Wates', 'Lumajang', 'Tanggul',
       'Barabai', 'Palabuhanratu', 'Cepu', 'Cibitung', 'Cikupa',
       'Amuntai', 'Rajapolah', 'Mentok', 'Parakan', 'Ngemplak',
       'Ambarawa', 'Cibadak', 'Adiwerna', 'Depok', 'Rantepao', 'Sumenep',
       'Karanganyar', 'Kasihan', 'Teluk Nibung', 'Srandakan', 'Wanasari',
       'Luwuk', 'Sinjai', 'Selogiri', 'Kediri', 'Jambi', 'Jatibarang',
       'Juwana', 'Kuningan', 'Bangil', 'Ciputat', 'Ambulu', 'Buduran',
       'Cibeureum', 'Mayong', 'Pandak', 'Panji', 'Bondowoso', 'Kisaran',
       'Padalarang', 'Cicalengka', 'Ciomas', 'Purwokerto', 'Jatiroto',
       'Kefamenanu', 'Banyuwangi', 'Gamping', 'Labuhan', 'Nganjuk',
       'Ambon', 'Kraksaan', 'Kroya', 'Poso', 'Temanggung', 'Weru',
       'Stabat', 'Trucuk', 'Payakumbuh', 'Tanggulangin', 'Randudongkal',
       'Lasem', 'Karangampel', 'Madiun', 'Margasari', 'Tasikmalaya',
       'Purwodadi', 'Pati', 'Astanajapura', 'Cikarang', 'Batu',
       'Sawangan', 'Denpasar', 'Sooko', 'Jatiwangi', 'Soe', 'Blora',
       'Majalaya', 'Palimanan', 'Labuhan Deli', 'Tarakan', 'Pasarkemis',
       'Sumedang', 'Metro', 'Kertosono', 'Porong', 'Ungaran', 'Jetis',
       'Ngawi', 'Langsa', 'Solok', 'Kemang', 'Lembang', 'Mendahara',
       'Subang', 'Pangkah', 'Surakarta', 'Ponorogo', 'Tanjung Morawa',
       'Baki', 'Pasuruan', 'Plered', 'Ngawen', 'Pundong', 'Wonopringgo',
       'Majenang', 'Cikampek', 'Galesong', 'Baturaja', 'Blitar',
       'Bengkulu', 'Biak', 'Mundu', 'Jeluko', 'Kadipaten', 'Indramayu',
       'Bandar', 'Serpong', 'Kedungwaru', 'Tulangan', 'Arjawinangun',
       'Magetan', 'Singaparna', 'Jati', 'Bireun', 'Tabanan', 'Tarub',
       'Pakisaji', 'Bantul', 'Slawi', 'Curup', 'Gondang', 'Jakarta',
       'Kencong', 'Palu', 'Makasar', 'Rancaekek', 'Katobu', 'Demak',
       'Klungkung', 'Tayu', 'Teluknaga', 'Krian', 'Manggar', 'Mojokerto',
       'Kualakapuas', 'Boyolangu', 'Tanete', 'Ngunut', 'Welahan',
       'Muncar', 'Margahayu', 'Prambanan', 'Kabanjahe'], dtype=object)

2. Berapa nilai AQI Value untuk setiap kota di Indonesia yang terdata?

In [25]:
aqi_values_indonesia = indonesia_cities_df[['City', 'AQI Value']]

display("AQI Value for each city in Indonesia:")
display(aqi_values_indonesia)

'AQI Value for each city in Indonesia:'

              City  AQI Value
31       Pontianak         44
96          Tidore         21
193    Sungaipenuh         17
215       Tarogong         88
353         Binjai         92
...            ...        ...
23156      Welahan         96
23167       Muncar         37
23282    Margahayu         98
23360    Prambanan         55
23424    Kabanjahe         22

[379 rows x 2 columns]

3. Berapa nilai rata-rata AQI Value untuk setiap kota di Indonesia tersebut?

In [26]:
average_aqi_per_city = indonesia_cities_df.groupby('City')['AQI Value'].mean()

display("Average AQI Value for each city in Indonesia:")
display(average_aqi_per_city)

'Average AQI Value for each city in Indonesia:'

City
Adiwerna        92.0
Ambarawa        86.0
Ambon           27.0
Ambulu          54.0
Amuntai         45.0
               ...
Wonogiri        51.0
Wonopringgo    163.0
Wonosari       174.0
Wonosobo        81.0
Yogyakarta      54.0
Name: AQI Value, Length: 379, dtype: float64

4. Bagaimana urutan Kota-kota tersebut dari rata-rata AQI Value terendah hingga tertinggi untuk menemukan 3 teratas?