In [1]:
import pandas as pd

url = "https://media.githubusercontent.com/media/KhalPrawira/Big-Data_Assignment/refs/heads/main/Dataset/Road%20Accident%20Data.csv"
df = pd.read_csv(url)

display(df.head())

,Accident_Index,Accident Date,Day_of_Week,Junction_Control,Junction_Detail,Accident_Severity,Latitude,Light_Conditions,Local_Authority_(District),Carriageway_Hazards,...,Number_of_Casualties,Number_of_Vehicles,Police_Force,Road_Surface_Conditions,Road_Type,Speed_limit,Time,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200901BS70001,1/1/2021,Thursday,Give way or uncontrolled,T or staggered junction,Serious,51.512273,Daylight,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Dry,One way street,30,15:11,Urban,Fine no high winds,Car
1,200901BS70002,1/5/2021,Monday,Give way or uncontrolled,Crossroads,Serious,51.514399,Daylight,Kensington and Chelsea,NaN,...,11,2,Metropolitan Police,Wet or damp,Single carriageway,30,10:59,Urban,Fine no high winds,Taxi/Private hire car
2,200901BS70003,1/4/2021,Sunday,Give way or uncontrolled,T or staggered junction,Slight,51.486668,Daylight,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Dry,Single carriageway,30,14:19,Urban,Fine no high winds,Taxi/Private hire car
3,200901BS70004,1/5/2021,Monday,Auto traffic signal,T or staggered junction,Serious,51.507804,Daylight,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Frost or ice,Single carriageway,30,8:10,Urban,Other,Motorcycle over 500cc
4,200901BS70005,1/6/2021,Tuesday,Auto traffic signal,Crossroads,Serious,51.482076,Darkness - lights lit,Kensington and Chelsea,NaN,...,1,2,Metropolitan Police,Dry,Single carriageway,30,17:25,Urban,Fine no high winds,Car

In [2]:
unique_local_authorities = df['Local_Authority_(District)'].unique()
print(unique_local_authorities)

['Kensington and Chelsea' 'Hammersmith and Fulham' 'Westminster'
 'Hounslow' 'City of London' 'Tower Hamlets' 'Hackney' 'Camden'
 'Southwark' 'Brent' 'Haringey' 'Islington' 'Barnet' 'Ealing' 'Newham'
 'London Airport (Heathrow)' 'Hillingdon' 'Waltham Forest' 'Redbridge'
 'Barking and Dagenham' 'Havering' 'Lambeth' 'Croydon' 'Wandsworth'
 'Bromley' 'Lewisham' 'Greenwich' 'Bexley' 'Harrow' 'Enfield' 'Sutton'
 'Merton' 'Kingston upon Thames' 'Richmond upon Thames' 'Eden' 'Copeland'
 'South Lakeland' 'Barrow-in-Furness' 'Allerdale' 'Carlisle' 'Fylde'
 'Blackpool' 'Wyre' 'Lancaster' 'Chorley' 'West Lancashire' 'South Ribble'
 'Preston' 'Blackburn with Darwen' 'Hyndburn' 'Ribble Valley' 'Burnley'
 'Pendle' 'Rossendale' 'Wirral' 'Sefton' 'St. Helens' 'Liverpool'
 'Knowsley' 'Manchester' 'Salford' 'Tameside' 'Stockport' 'Bolton' 'Wigan'
 'Trafford' 'Bury' 'Rochdale' 'Oldham' 'Vale Royal' 'Crewe and Nantwich'
 'Halton' 'Chester' 'Macclesfield' 'Cheshire East' 'Warrington'
 'Crewe and ntwich' 'Cheshire West and Chester' 'Congleton'
 'Ellesmere Port and Neston' 'Wansbeck' 'Blyth Valley' 'North Tyneside'
 'Newcastle upon Tyne' 'Tynedale' 'Alnwick' 'South Tyneside' 'Gateshead'
 'Castle Morpeth' 'Sunderland' 'Berwick-upon-Tweed' 'Northumberland'
 'Durham' 'County Durham' 'Easington' 'Chester-le-Street' 'Derwentside'
 'Wear Valley' 'Teesdale' 'Darlington' 'Sedgefield' 'Hambleton' 'York'
 'Craven' 'Richmondshire' 'Scarborough' 'Selby' 'Harrogate' 'Ryedale'
 'Calderdale' 'Bradford' 'Wakefield' 'Leeds' 'Kirklees' 'Doncaster'
 'Rotherham' 'Barnsley' 'Sheffield' 'North East Lincolnshire'
 'North Lincolnshire' 'East Riding of Yorkshire'
 'Kingston upon Hull, City of' 'Hartlepool' 'Redcar and Cleveland'
 'Middlesbrough' 'Stockton-on-Tees' 'Birmingham' 'Wolverhampton' 'Walsall'
 'Dudley' 'Sandwell' 'Solihull' 'Coventry' 'Lichfield' 'Stafford'
 'Stoke-on-Trent' 'East Staffordshire' 'Newcastle-under-Lyme'
 'Cannock Chase' 'South Staffordshire' 'Tamworth'
 'Staffordshire Moorlands' 'Wychavon' 'Malvern Hills' 'Worcester'
 'Wyre Forest' 'Herefordshire, County of' 'Shropshire' 'Redditch'
 'Bromsgrove' 'South Shropshire' 'North Shropshire'
 'Shrewsbury and Atcham' 'Oswestry' 'Telford and Wrekin' 'Bridgnorth'
 'Stratford-upon-Avon' 'Warwick' 'North Warwickshire' 'Rugby'
 'Nuneaton and Bedworth' 'Amber Valley' 'Erewash' 'Bolsover'
 'Derbyshire Dales' 'High Peak' 'Chesterfield' 'North East Derbyshire'
 'Derby' 'South Derbyshire' 'Ashfield' 'Mansfield' 'Newark and Sherwood'
 'Nottingham' 'Gedling' 'Bassetlaw' 'Broxtowe' 'Rushcliffe'
 'South Kesteven' 'South Holland' 'North Kesteven' 'Lincoln'
 'East Lindsey' 'Boston' 'West Lindsey' 'Leicester' 'Melton' 'Charnwood'
 'Blaby' 'Harborough' 'Rutland' 'Hinckley and Bosworth'
 'North West Leicestershire' 'Oadby and Wigston' 'Corby' 'Wellingborough'
 'Daventry' 'Kettering' 'East Northamptonshire' 'Northampton'
 'South Northamptonshire' 'South Cambridgeshire' 'Cambridge'
 'Peterborough' 'East Cambridgeshire' 'Huntingdonshire' 'Fenland'
 'Great Yarmouth' 'Norwich' 'Breckland' 'Broadland'
 "King's Lynn and West Norfolk" 'South Norfolk' 'North Norfolk'
 'Mid Suffolk' 'Suffolk Coastal' 'Forest Heath' 'St. Edmundsbury'
 'Babergh' 'Ipswich' 'Waveney' 'Bedford' 'Mid Bedfordshire'
 'Central Bedfordshire' 'South Bedfordshire' 'Luton' 'East Hertfordshire'
 'Broxbourne' 'Welwyn Hatfield' 'North Hertfordshire' 'Watford'
 'Three Rivers' 'Dacorum' 'Hertsmere' 'St. Albans' 'Stevege' 'Stevenage'
 'Braintree' 'Chelmsford' 'Epping Forest' 'Maldon' 'Tendring' 'Basildon'
 'Brentwood' 'Southend-on-Sea' 'Colchester' 'Uttlesford' 'Harlow'
 'Thurrock' 'Castle Point' 'Rochford' 'Aylesbury Vale' 'Wycombe'
 'South Bucks' 'Chiltern' 'Milton Keynes' 'South Oxfordshire' 'Slough'
 'Cherwell' 'Oxford' 'Vale of White Horse' 'West Oxfordshire'
 'West Berkshire' 'Windsor and Maidenhead' 'Bracknell Forest' 'Reading'
 'Wokingham' 'Rushmoor' 'Basingstoke and Deane' 'Isle of Wight' 'Hart'
 'Portsmouth' 'Fareham' 'Southampton' 'East Hampshire' 'Winchester'
 'Gosport' 'New Forest' 'Eastleigh' 'Test Valley' 'Havant' 'Elmbridge'
 'Mole Valley' 'Runnymede' 'Epsom and Ewell' 'Guildford' 'Spelthorne'
 'Reigate and Banstead' 'Waverley' 'Surrey Heath' 'Woking' 'Tandridge'
 'Medway' 'Dartford' 'Gravesham' 'Tonbridge and Malling' 'Canterbury'
 'Thanet' 'Swale' 'Maidstone' 'Tunbridge Wells' 'Sevenoaks' 'Shepway'
 'Ashford' 'Dover' 'Brighton and Hove' 'Worthing' 'Hastings' 'Horsham'
 'Wealden' 'Lewes' 'Mid Sussex' 'Eastbourne' 'Crawley' 'Rother' 'Arun'
 'Chichester' 'Adur' 'Cornwall' 'Kerrier' 'Penwith' 'North Cornwall'
 'Caradon' 'Plymouth' 'Torbay' 'North Devon' 'Torridge' 'Exeter'
 'South Hams' 'West Devon' 'Restormel' 'Carrick' 'Teignbridge'
 'East Devon' 'Mid Devon' 'Mendip' 'South Gloucestershire'
 'North Somerset' 'Sedgemoor' 'Taunton Deane' 'Bristol, City of'
 'South Somerset' 'West Somerset' 'Bath and North East Somerset'
 'Cotswold' 'Gloucester' 'Stroud' 'Tewkesbury' 'Cheltenham'
 'Forest of Dean' 'Swindon' 'Wiltshire' 'West Wiltshire' 'Salisbury'
 'Kennet' 'North Wiltshire' 'Bournemouth' 'West Dorset' 'Poole'
 'East Dorset' 'Christchurch' 'Purbeck' 'North Dorset'
 'Weymouth and Portland' 'Flintshire' 'Denbighshire' 'Wrexham' 'Conwy'
 'Gwynedd' 'Isle of Anglesey' 'Caerphilly' 'Torfaen' 'Newport'
 'Blaeu Gwent' 'Blaenau Gwent' 'Monmouthshire' 'Rhondda, Cynon, Taff'
 'Merthyr Tydfil' 'Cardiff' 'The Vale of Glamorgan' 'Bridgend'
 'Neath Port Talbot' 'Swansea' 'Carmarthenshire' 'Ceredigion'
 'Pembrokeshire' 'Powys' 'Highland' 'Western Isles' 'Orkney Islands'
 'Shetland Islands' 'Moray' 'Aberdeenshire' 'Aberdeen City' 'Angus'
 'Perth and Kinross' 'Dundee City' 'Fife' 'Edinburgh, City of'
 'East Lothian' 'Scottish Borders' 'West Lothian' 'Midlothian' 'Falkirk'
 'Stirling' 'Clackmannshire' 'Clackmannanshire' 'Glasgow City'
 'East Dunbartonshire' 'East Renfrewshire' 'Renfrewshire' 'Inverclyde'
 'Argyll and Bute' 'West Dunbartonshire' 'North Lanarkshire'
 'North Larkshire' 'South Lanarkshire' 'South Larkshire' 'North Ayrshire'
 'East Ayrshire' 'South Ayrshire' 'Dumfries and Galloway']

In [3]:
print("Relevant columns in the existing dataframe:")
print(df[['Weather_Conditions', 'Road_Surface_Conditions', 'Light_Conditions']].head())

Relevant columns in the existing dataframe:
   Weather_Conditions Road_Surface_Conditions       Light_Conditions
0  Fine no high winds                     Dry               Daylight
1  Fine no high winds             Wet or damp               Daylight
2  Fine no high winds                     Dry               Daylight
3               Other            Frost or ice               Daylight
4  Fine no high winds                     Dry  Darkness - lights lit

In [4]:
import requests
from datetime import date, timedelta

API_KEY = "XL23858CQULKT2XR5NHAAE8QT"
BASE_URL = "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/"

locations = ["Hackney,UK", "Camden,UK"]
start_date = date(2023, 1, 1)
end_date = date(2023, 1, 31)

weather_data = []

for location in locations:
    current_date = start_date
    while current_date <= end_date:
        date_str = current_date.strftime("%Y-%m-%d")
        url = f"{BASE_URL}{location}/{date_str}/{date_str}?key={API_KEY}&unitGroup=metric&include=days"

        try:
            response = requests.get(url)
            response.raise_for_status()
            data = response.json()
            weather_data.append({'location': location, 'date': date_str, 'data': data})

        except requests.exceptions.RequestException as e:
            print(f"Error fetching data for {location} on {date_str}: {e}")

        current_date += timedelta(days=1)

print(f"Successfully retrieved weather data for {len(weather_data)} days.")

Successfully retrieved weather data for 62 days.

In [5]:
import pandas as pd

processed_weather_data = []

for entry in weather_data:
    location = entry['location'].split(',')[0]
    date_str = entry['date']
    if entry['data'] and 'days' in entry['data'] and entry['data']['days']:
        daily_data = entry['data']['days'][0]

        tempmax = daily_data.get('tempmax')
        tempmin = daily_data.get('tempmin')
        temp = daily_data.get('temp')
        precip = daily_data.get('precip')
        precipprob = daily_data.get('precipprob')
        preciptype = daily_data.get('preciptype')
        snow = daily_data.get('snow')
        snowdepth = daily_data.get('snowdepth')
        windgust = daily_data.get('windgust')
        windspeed = daily_data.get('windspeed')
        winddir = daily_data.get('winddir')
        pressure = daily_data.get('pressure')
        visibility = daily_data.get('visibility')
        cloudcover = daily_data.get('cloudcover')
        solarradiation = daily_data.get('solarradiation')
        solarenergy = daily_data.get('solarenergy')
        uvindex = daily_data.get('uvindex')
        conditions = daily_data.get('conditions')
        description = daily_data.get('description')
        icon = daily_data.get('icon')


        processed_weather_data.append({
            'location': location,
            'date': date_str,
            'tempmax': tempmax,
            'tempmin': tempmin,
            'temp': temp,
            'precip': precip,
            'precipprob': precipprob,
            'preciptype': preciptype,
            'snow': snow,
            'snowdepth': snowdepth,
            'windgust': windgust,
            'windspeed': windspeed,
            'winddir': winddir,
            'pressure': pressure,
            'visibility': visibility,
            'cloudcover': cloudcover,
            'solarradiation': solarradiation,
            'solarenergy': solarenergy,
            'uvindex': uvindex,
            'conditions': conditions,
            'description': description,
            'icon': icon,
        })

weather_df = pd.DataFrame(processed_weather_data)

weather_df['date'] = pd.to_datetime(weather_df['date'])

display(weather_df.head())

,location,date,tempmax,tempmin,temp,precip,precipprob,preciptype,snow,snowdepth,...,winddir,pressure,visibility,cloudcover,solarradiation,solarenergy,uvindex,conditions,description,icon
0,Hackney,2023-01-01,8.6,6.2,7.4,14.054,100.0,[rain],0.0,0.0,...,215.3,1003.7,27.7,81.6,23.1,1.8,2.0,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain
1,Hackney,2023-01-02,5.9,1.4,3.8,0.877,100.0,[rain],0.0,0.0,...,244.9,1015.3,26.6,44.4,40.8,3.6,2.0,"Rain, Partially cloudy",Partly cloudy throughout the day with rain cle...,rain
2,Hackney,2023-01-03,11.1,0.6,6.7,6.456,100.0,[rain],0.0,0.0,...,190.6,1013.4,21.0,87.4,8.7,0.8,1.0,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain
3,Hackney,2023-01-04,11.3,9.1,10.4,5.685,100.0,[rain],0.0,0.0,...,247.9,1009.3,25.2,76.7,29.2,2.7,2.0,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain
4,Hackney,2023-01-05,10.8,7.5,9.3,1.689,100.0,[rain],0.0,0.0,...,226.1,1014.0,28.1,97.3,13.8,1.1,1.0,"Rain, Overcast",Cloudy skies throughout the day with a chance ...,rain

In [6]:
weather_df.to_csv('processed_weather_data.csv', index=False)

print("Processed weather data exported to 'processed_weather_data.csv'")

Processed weather data exported to 'processed_weather_data.csv'

In [7]:
df_renamed = df.rename(columns={'Accident Date': 'date', 'Local_Authority_(District)': 'location'})

df_renamed['date'] = pd.to_datetime(df_renamed['date'], errors='coerce')
weather_df['date'] = pd.to_datetime(weather_df['date'])

print("Date range of accident data:")
print(f"Min date: {df_renamed['date'].min()}, Max date: {df_renamed['date'].max()}")
print("\nDate range of weather data:")
print(f"Min date: {weather_df['date'].min()}, Max date: {weather_df['date'].max()}")


accident_locations_to_merge = ['Hackney', 'Camden']
df_filtered = df_renamed[df_renamed['location'].isin(accident_locations_to_merge)].copy()

if 'Accident_Index' in df_filtered.columns:
    df_filtered = df_filtered.drop(columns=['Accident_Index'])


merged_df = pd.merge(df_filtered, weather_df, on=['date', 'location'], how='outer')

display(merged_df.head())

print("\nColumns in merged_df and their missing value counts:")
print(merged_df.isnull().sum())

Date range of accident data:
Min date: 2021-01-01 00:00:00, Max date: 2022-12-31 00:00:00

Date range of weather data:
Min date: 2023-01-01 00:00:00, Max date: 2023-01-31 00:00:00

,date,Day_of_Week,Junction_Control,Junction_Detail,Accident_Severity,Latitude,Light_Conditions,location,Carriageway_Hazards,Longitude,...,winddir,pressure,visibility,cloudcover,solarradiation,solarenergy,uvindex,conditions,description,icon
0,2021-01-01,Thursday,Data missing or out of range,Not at junction or within 20 metres,Serious,51.543017,Daylight,Camden,NaN,-0.137258,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-01-01,Thursday,Give way or uncontrolled,T or staggered junction,Slight,51.559328,Daylight,Camden,NaN,-0.197040,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-01-01,Thursday,Give way or uncontrolled,T or staggered junction,Slight,51.563718,Darkness - lights lit,Hackney,NaN,-0.060663,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-01-01,Thursday,Auto traffic signal,Crossroads,Slight,51.540314,Darkness - lights lit,Hackney,NaN,-0.070167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-01-02,Friday,Give way or uncontrolled,T or staggered junction,Slight,51.542857,Daylight,Camden,NaN,-0.144187,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Columns in merged_df and their missing value counts:
date                          0
Day_of_Week                  62
Junction_Control             62
Junction_Detail              62
Accident_Severity            62
Latitude                     62
Light_Conditions             62
location                      0
Carriageway_Hazards        3281
Longitude                    62
Number_of_Casualties         62
Number_of_Vehicles           62
Police_Force                 62
Road_Surface_Conditions      62
Road_Type                    63
Speed_limit                  62
Time                         62
Urban_or_Rural_Area          62
Weather_Conditions           73
Vehicle_Type                 62
tempmax                    3254
tempmin                    3254
temp                       3254
precip                     3254
precipprob                 3254
preciptype                 3266
snow                       3256
snowdepth                  3254
windgust                   3254
windspeed                  3254
winddir                    3254
pressure                   3254
visibility                 3254
cloudcover                 3254
solarradiation             3254
solarenergy                3254
uvindex                    3254
conditions                 3254
description                3254
icon                       3254
dtype: int64

In [8]:
# Export the merged dataframe to a CSV file
merged_df.to_csv('merged_accident_weather_data.csv', index=False)

print("Merged data exported to 'merged_accident_weather_data.csv'")

Merged data exported to 'merged_accident_weather_data.csv'